import Foundation
import Combine

enum L10nKey: String {
    case desktop, fullscreen
    case renameDesktop, showWindow, alwaysOnTop, launchAtLogin
    case hideWindow, language, about, quit
    case aboutText, version, openProjectFolder, loginItemError
    case compactWindow, indexOnly
    case alignMenu, alignLeft, alignRight
    case desktopsSettings, uiSettings, opacity, add, contrast, goTo
}

@MainActor
final class L10n: ObservableObject {
    static let shared = L10n()

    @Published var lang: String {
        didSet { UserDefaults.standard.set(lang, forKey: "AppLanguage") }
    }

    private init() {
        lang = UserDefaults.standard.string(forKey: "AppLanguage") ?? "en"
    }

    static let languages: [(code: String, name: String)] = [
        ("en", "English"),
        ("ru", "Русский"),
        ("es", "Español"),
        ("de", "Deutsch"),
        ("fr", "Français"),
        ("it", "Italiano"),
        ("pt", "Português"),
        ("zh", "中文"),
        ("ja", "日本語"),
        ("ko", "한국어"),
    ]

    func t(_ key: L10nKey) -> String {
        Self.tables[lang]?[key] ?? Self.tables["en"]![key]!
    }

    private static let tables: [String: [L10nKey: String]] = [
        "en": [
            .desktop: "Desktop",
            .fullscreen: "Fullscreen",
            .goTo: "Go to…",
            .renameDesktop: "Rename this desktop…",
            .showWindow: "Show window",
            .alwaysOnTop: "Always on top",
            .launchAtLogin: "Launch at login",
            .hideWindow: "Hide window",
            .language: "Language",
            .about: "About…",
            .quit: "Quit",
            .version: "Version",
            .openProjectFolder: "Open project folder",
            .loginItemError: "Failed to change login item",
            .compactWindow: "Compact window",
            .indexOnly: "Number only",
            .contrast: "Contrast",
            .alignMenu: "Alignment",
            .alignLeft: "Left",
            .alignRight: "Right",
            .desktopsSettings: "Desktops settings…",
            .uiSettings: "UI settings…",
            .opacity: "Opacity",
            .add: "Add",
            .aboutText: "Shows the number of the current desktop (Space) in a small floating window. Click the window to give the desktop your own name.",
        ],
        "ru": [
            .desktop: "Десктоп",
            .fullscreen: "Полный экран",
            .goTo: "Перейти к…",
            .renameDesktop: "Переименовать этот десктоп…",
            .showWindow: "Показывать окошко",
            .alwaysOnTop: "Поверх всех окон",
            .launchAtLogin: "Запускать при входе в систему",
            .hideWindow: "Скрыть окошко",
            .language: "Язык",
            .about: "О программе…",
            .quit: "Выход",
            .version: "Версия",
            .openProjectFolder: "Открыть папку проекта",
            .loginItemError: "Не удалось изменить автозапуск",
            .compactWindow: "Компактное окошко",
            .indexOnly: "Только номер",
            .contrast: "Контраст",
            .alignMenu: "Выравнивание",
            .alignLeft: "Слева",
            .alignRight: "Справа",
            .desktopsSettings: "Настройки десктопов…",
            .uiSettings: "Настройки интерфейса…",
            .opacity: "Непрозрачность",
            .add: "Добавить",
            .aboutText: "Показывает порядковый номер текущего десктопа (Space) в маленьком плавающем окошке. Кликните по окошку, чтобы дать десктопу своё имя.",
        ],
        "es": [
            .desktop: "Escritorio",
            .fullscreen: "Pantalla completa",
            .goTo: "Ir a…",
            .renameDesktop: "Renombrar este escritorio…",
            .showWindow: "Mostrar ventana",
            .alwaysOnTop: "Siempre visible",
            .launchAtLogin: "Abrir al iniciar sesión",
            .hideWindow: "Ocultar ventana",
            .language: "Idioma",
            .about: "Acerca de…",
            .quit: "Salir",
            .version: "Versión",
            .openProjectFolder: "Abrir carpeta del proyecto",
            .loginItemError: "No se pudo cambiar el inicio automático",
            .compactWindow: "Ventana compacta",
            .indexOnly: "Solo el número",
            .contrast: "Contraste",
            .alignMenu: "Alineación",
            .alignLeft: "Izquierda",
            .alignRight: "Derecha",
            .desktopsSettings: "Ajustes de escritorios…",
            .uiSettings: "Ajustes de interfaz…",
            .opacity: "Opacidad",
            .add: "Añadir",
            .aboutText: "Muestra el número del escritorio (Space) actual en una pequeña ventana flotante. Haz clic en la ventana para darle tu propio nombre al escritorio.",
        ],
        "de": [
            .desktop: "Schreibtisch",
            .fullscreen: "Vollbild",
            .goTo: "Gehe zu…",
            .renameDesktop: "Diesen Schreibtisch umbenennen…",
            .showWindow: "Fenster anzeigen",
            .alwaysOnTop: "Immer im Vordergrund",
            .launchAtLogin: "Beim Anmelden starten",
            .hideWindow: "Fenster ausblenden",
            .language: "Sprache",
            .about: "Über…",
            .quit: "Beenden",
            .version: "Version",
            .openProjectFolder: "Projektordner öffnen",
            .loginItemError: "Autostart konnte nicht geändert werden",
            .compactWindow: "Kompaktes Fenster",
            .indexOnly: "Nur Nummer",
            .contrast: "Kontrast",
            .alignMenu: "Ausrichtung",
            .alignLeft: "Links",
            .alignRight: "Rechts",
            .desktopsSettings: "Schreibtisch-Einstellungen…",
            .uiSettings: "Oberflächen-Einstellungen…",
            .opacity: "Deckkraft",
            .add: "Hinzufügen",
            .aboutText: "Zeigt die Nummer des aktuellen Schreibtischs (Space) in einem kleinen schwebenden Fenster. Klicken Sie auf das Fenster, um dem Schreibtisch einen eigenen Namen zu geben.",
        ],
        "fr": [
            .desktop: "Bureau",
            .fullscreen: "Plein écran",
            .goTo: "Aller à…",
            .renameDesktop: "Renommer ce bureau…",
            .showWindow: "Afficher la fenêtre",
            .alwaysOnTop: "Toujours au premier plan",
            .launchAtLogin: "Lancer à l'ouverture de session",
            .hideWindow: "Masquer la fenêtre",
            .language: "Langue",
            .about: "À propos…",
            .quit: "Quitter",
            .version: "Version",
            .openProjectFolder: "Ouvrir le dossier du projet",
            .loginItemError: "Impossible de modifier le démarrage automatique",
            .compactWindow: "Fenêtre compacte",
            .indexOnly: "Numéro uniquement",
            .contrast: "Contraste",
            .alignMenu: "Alignement",
            .alignLeft: "Gauche",
            .alignRight: "Droite",
            .desktopsSettings: "Réglages des bureaux…",
            .uiSettings: "Réglages de l'interface…",
            .opacity: "Opacité",
            .add: "Ajouter",
            .aboutText: "Affiche le numéro du bureau (Space) actuel dans une petite fenêtre flottante. Cliquez sur la fenêtre pour donner votre propre nom au bureau.",
        ],
        "it": [
            .desktop: "Scrivania",
            .fullscreen: "Schermo intero",
            .goTo: "Vai a…",
            .renameDesktop: "Rinomina questa scrivania…",
            .showWindow: "Mostra finestra",
            .alwaysOnTop: "Sempre in primo piano",
            .launchAtLogin: "Avvia all'accesso",
            .hideWindow: "Nascondi finestra",
            .language: "Lingua",
            .about: "Informazioni…",
            .quit: "Esci",
            .version: "Versione",
            .openProjectFolder: "Apri cartella del progetto",
            .loginItemError: "Impossibile modificare l'avvio automatico",
            .compactWindow: "Finestra compatta",
            .indexOnly: "Solo numero",
            .contrast: "Contrasto",
            .alignMenu: "Allineamento",
            .alignLeft: "Sinistra",
            .alignRight: "Destra",
            .desktopsSettings: "Impostazioni scrivanie…",
            .uiSettings: "Impostazioni interfaccia…",
            .opacity: "Opacità",
            .add: "Aggiungi",
            .aboutText: "Mostra il numero della scrivania (Space) corrente in una piccola finestra flottante. Fai clic sulla finestra per dare alla scrivania un nome personalizzato.",
        ],
        "pt": [
            .desktop: "Mesa",
            .fullscreen: "Tela cheia",
            .goTo: "Ir para…",
            .renameDesktop: "Renomear esta mesa…",
            .showWindow: "Mostrar janela",
            .alwaysOnTop: "Sempre visível",
            .launchAtLogin: "Iniciar ao fazer login",
            .hideWindow: "Ocultar janela",
            .language: "Idioma",
            .about: "Sobre…",
            .quit: "Sair",
            .version: "Versão",
            .openProjectFolder: "Abrir pasta do projeto",
            .loginItemError: "Não foi possível alterar a inicialização automática",
            .compactWindow: "Janela compacta",
            .indexOnly: "Apenas o número",
            .contrast: "Contraste",
            .alignMenu: "Alinhamento",
            .alignLeft: "Esquerda",
            .alignRight: "Direita",
            .desktopsSettings: "Ajustes das mesas…",
            .uiSettings: "Ajustes de interface…",
            .opacity: "Opacidade",
            .add: "Adicionar",
            .aboutText: "Mostra o número da mesa (Space) atual em uma pequena janela flutuante. Clique na janela para dar seu próprio nome à mesa.",
        ],
        "zh": [
            .desktop: "桌面",
            .fullscreen: "全屏",
            .goTo: "前往…",
            .renameDesktop: "重命名此桌面…",
            .showWindow: "显示窗口",
            .alwaysOnTop: "置顶显示",
            .launchAtLogin: "登录时启动",
            .hideWindow: "隐藏窗口",
            .language: "语言",
            .about: "关于…",
            .quit: "退出",
            .version: "版本",
            .openProjectFolder: "打开项目文件夹",
            .loginItemError: "无法更改登录启动项",
            .compactWindow: "紧凑窗口",
            .indexOnly: "仅显示编号",
            .contrast: "对比色",
            .alignMenu: "对齐",
            .alignLeft: "左",
            .alignRight: "右",
            .desktopsSettings: "桌面设置…",
            .uiSettings: "界面设置…",
            .opacity: "不透明度",
            .add: "添加",
            .aboutText: "在小型悬浮窗口中显示当前桌面（Space）的编号。点击窗口即可为桌面设置自定义名称。",
        ],
        "ja": [
            .desktop: "デスクトップ",
            .fullscreen: "フルスクリーン",
            .goTo: "移動…",
            .renameDesktop: "このデスクトップの名前を変更…",
            .showWindow: "ウィンドウを表示",
            .alwaysOnTop: "常に最前面",
            .launchAtLogin: "ログイン時に起動",
            .hideWindow: "ウィンドウを隠す",
            .language: "言語",
            .about: "このアプリについて…",
            .quit: "終了",
            .version: "バージョン",
            .openProjectFolder: "プロジェクトフォルダを開く",
            .loginItemError: "ログイン項目を変更できませんでした",
            .compactWindow: "コンパクト表示",
            .indexOnly: "番号のみ",
            .contrast: "コントラスト",
            .alignMenu: "配置",
            .alignLeft: "左",
            .alignRight: "右",
            .desktopsSettings: "デスクトップ設定…",
            .uiSettings: "UI設定…",
            .opacity: "不透明度",
            .add: "追加",
            .aboutText: "現在のデスクトップ（Space）の番号を小さなフローティングウィンドウに表示します。ウィンドウをクリックすると、デスクトップに好きな名前を付けられます。",
        ],
        "ko": [
            .desktop: "데스크탑",
            .fullscreen: "전체 화면",
            .goTo: "이동…",
            .renameDesktop: "이 데스크탑 이름 변경…",
            .showWindow: "창 표시",
            .alwaysOnTop: "항상 위에 표시",
            .launchAtLogin: "로그인 시 시작",
            .hideWindow: "창 숨기기",
            .language: "언어",
            .about: "정보…",
            .quit: "종료",
            .version: "버전",
            .openProjectFolder: "프로젝트 폴더 열기",
            .loginItemError: "로그인 항목을 변경할 수 없습니다",
            .compactWindow: "컴팩트 창",
            .indexOnly: "번호만",
            .contrast: "대비",
            .alignMenu: "정렬",
            .alignLeft: "왼쪽",
            .alignRight: "오른쪽",
            .desktopsSettings: "데스크탑 설정…",
            .uiSettings: "UI 설정…",
            .opacity: "불투명도",
            .add: "추가",
            .aboutText: "현재 데스크탑(Space)의 번호를 작은 플로팅 창에 표시합니다. 창을 클릭하면 데스크탑에 원하는 이름을 지정할 수 있습니다.",
        ],
    ]
}

#if DEV_BUILD
// Dev-примечания для About: только в сборке с -dev, в публичный бинарник не попадают.
extension L10n {
    func devSuffix() -> String {
        lang == "ru"
            ? "Локальная dev-сборка этого компьютера.\nСобрано с помощью Claude Code.\n\nПапка проекта:\n{path}"
            : "Local dev build for this Mac.\nBuilt with Claude Code.\n\nProject folder:\n{path}"
    }
}
#endif
